# Spring Boot application configuration
datasource:
  url: jdbc:postgresql://localhost:5433/zerotrustdb
  username: postgres
  password: password
  driver-class-name: org.postgresql.Driver
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5433/zerotrustdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: true
jwt:
  secret: your_jwt_secret_here
